### ISSUE TITLE
右のタグがABC順で10個までしか表示されない

### ISSUE THREAD

**Issue by nbtakusaito** [nijibox/textbox#24]
議事録のタグがないのかなーと思ったら10個までしか出てなかった。

どうなればベストかわからないっすけど、とりあえず表記

**Comment by attakei** [comment]
https://github.com/nijibox/textbox/blob/master/app/ArticleTag.php#L32

サイドバーにあるタグのリストを出すときにやっていることがこれだけなのが原因ですね。
というわけで、

- [ ] ホットなタグを示せるように、「最近更新があったタグ10件」にする
- [ ] 「すべてのタグ」リンクを用意してタグだけのページを作る

この辺があれば解消されそう？

**Comment by nbtakusaito** [comment]
確かに、その２つあれば十分な気がします！

**Comment by attakei** [comment]
@nbtakusaito 対応したコードを社内環境へも反映しました
