### ISSUE TITLE
編集から更新をかけるとSlackに通知が飛ぶ

### ISSUE THREAD

**Issue by KazukiMitani** [nijibox/textbox#52]
一度公開した記事を編集してもう一度公開するとSlackに通知が飛んでしまう。

- 一度公開になった記事にフラグを持って2度めは通知しない
- 編集開始時に現在のステータスをとって、公開している記事の編集だった場合、通知処理を走らせない

みたいな感じで実装されると嬉しいっす！

**Comment by attakei** [comment]
とりあえず、最短経路で改修中

**Comment by attakei** [comment]
改修完了しました
@KazukiMitani StaQにて反映確認をお願いします。OKならcloseしてください。
